variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
    SolutionBaseName: 'Dfc.App.ActionPlans'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    displayName: "Test & packate ARM template(s)"
    steps:
      - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
        parameters:
          ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
          SolutionBaseName: '${{ variables.SolutionBaseName }}'
  
  - job: BuildDotNetCore
    displayName: Build-DotNetCore


      steps:
      - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
        parameters:
          SolutionBaseName: $(SolutionBaseName)
          BuildPlatform: 'any cpu'
          BuildConfiguration: 'release'
          DotNetCoreVersion: '3.1.100'
          PublishWebApp: true
          TestSuffix: UnitTests
